'use client';
import { useState } from 'react';
import { Send, X } from 'lucide-react';
import { sendJobInvitation } from '@/server/actions/dashboard/employer/invitations/sendJobInvitation';

export default function InviteCandidateDialog({ candidateId, jobs }: { candidateId: string; jobs: { id: string; title: string }[] }) {
  const [open, setOpen] = useState(false); const [jobId, setJobId] = useState(jobs[0]?.id ?? ''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState<string | null>(null);
  async function submit() { if (!jobId) return setFeedback('Select a job first.'); setBusy(true); setFeedback(null); const result = await sendJobInvitation({ jobId, candidateId, message }); setBusy(false); if (!result.success) return setFeedback(result.error); setFeedback('Invitation sent successfully.'); setMessage(''); setTimeout(() => { setOpen(false); setFeedback(null); }, 900); }
  if (!jobs.length) return null;
  return <><button type="button" onClick={() => setOpen(true)} className="inline-flex h-9 items-center gap-2 rounded-lg border px-4 text-sm font-medium hover:bg-muted"><Send className="size-4"/>Invite to apply</button>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-2xl border bg-card p-6 shadow-xl"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Invite candidate</h2><p className="mt-1 text-sm text-muted-foreground">Choose one of your published jobs and send a direct invitation.</p></div><button type="button" onClick={() => setOpen(false)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><X className="size-4"/></button></div><div className="mt-6 space-y-4"><div><label htmlFor="invite-job" className="text-sm font-medium">Job</label><select id="invite-job" value={jobId} onChange={e => setJobId(e.target.value)} className="mt-2 h-10 w-full rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/30">{jobs.map(job => <option key={job.id} value={job.id}>{job.title}</option>)}</select></div><div><label htmlFor="invite-message" className="text-sm font-medium">Message <span className="text-muted-foreground">(optional)</span></label><textarea id="invite-message" value={message} onChange={e => setMessage(e.target.value)} rows={5} maxLength={1000} placeholder="Tell the candidate why you think this opportunity could be a good fit." className="mt-2 w-full resize-none rounded-lg border bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"/></div>{feedback && <div className="rounded-lg bg-muted p-3 text-sm">{feedback}</div>}<div className="flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="inline-flex h-9 items-center rounded-lg border px-4 text-sm font-medium hover:bg-muted">Cancel</button><button type="button" disabled={busy} onClick={submit} className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground hover:bg-primary/90 disabled:opacity-50"><Send className="size-4"/>{busy ? 'Sending…' : 'Send invitation'}</button></div></div></div></div>}</>;
}
