import Link from 'next/link';
import { BriefcaseBusiness, Clock3, MapPin, UserRound } from 'lucide-react';
import { getEmployerInvitations } from '@/server/actions/dashboard/employer/invitations/getEmployerInvitations';

function statusClass(status: string) { return status === 'ACCEPTED' ? 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-400' : status === 'DECLINED' || status === 'CANCELLED' ? 'bg-red-500/10 text-red-700 dark:text-red-400' : status === 'EXPIRED' ? 'bg-muted text-muted-foreground' : 'bg-amber-500/10 text-amber-700 dark:text-amber-400'; }

export default async function EmployerInvitationsPage() {
  const invitations = await getEmployerInvitations();
  return <main className="mx-auto w-full max-w-6xl space-y-6 p-4 lg:p-8">
    <div><p className="text-sm font-medium text-primary">Communication</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Invitations</h1><p className="mt-2 text-sm text-muted-foreground">Track candidates your company has invited to apply for its jobs.</p></div>
    {invitations.length === 0 ? <section className="rounded-2xl border bg-card p-8 text-center"><BriefcaseBusiness className="mx-auto size-9 text-muted-foreground"/><h2 className="mt-4 font-semibold">No invitations yet</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Discover candidates and send them a direct invitation when you find a strong match.</p><Link href="/dashboard/employer/candidates" className="mt-5 inline-flex h-9 items-center rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground hover:bg-primary/90">Browse candidates</Link></section> : <section className="overflow-hidden rounded-2xl border bg-card"><div className="divide-y">{invitations.map(inv => { const p = inv.recipient.jobSeeker; return <article key={inv.id} className="p-5 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div className="flex min-w-0 gap-4"><div className="flex size-12 shrink-0 items-center justify-center overflow-hidden rounded-full bg-muted">{p?.profilePhotoUrl || inv.recipient.image ? <img src={p?.profilePhotoUrl ?? inv.recipient.image ?? ''} alt={inv.recipient.name} className="size-full object-cover"/> : <UserRound className="size-5 text-muted-foreground"/>}</div><div className="min-w-0"><Link href={`/dashboard/employer/candidates/${inv.recipient.id}`} className="font-semibold hover:text-primary">{inv.recipient.name}</Link><p className="mt-1 text-sm text-muted-foreground">{p?.currentRole ?? p?.headline ?? 'Job seeker'}</p><div className="mt-2 flex flex-wrap gap-3 text-xs text-muted-foreground">{p?.location && <span className="inline-flex items-center gap-1"><MapPin className="size-3.5"/>{p.location}</span>}<span className="inline-flex items-center gap-1"><BriefcaseBusiness className="size-3.5"/>{inv.job.title}</span></div></div></div><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-medium ${statusClass(inv.status)}`}>{inv.status}</span></div>{inv.message && <div className="mt-4 rounded-xl bg-muted/50 p-4 text-sm leading-6 text-muted-foreground">“{inv.message}”</div>}<div className="mt-4 flex flex-wrap items-center gap-4 text-xs text-muted-foreground"><span>Sent {inv.createdAt.toLocaleDateString('en-NG')}</span>{inv.expiresAt && inv.status === 'PENDING' && <span className="inline-flex items-center gap-1"><Clock3 className="size-3.5"/>Expires {inv.expiresAt.toLocaleDateString('en-NG')}</span>}<Link href={`/dashboard/employer/candidates/${inv.recipient.id}`} className="font-medium text-primary hover:underline">View candidate</Link></div></article>; })}</div></section>}
  </main>;
}
